[package]
name = "mfhx_web"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0.216", features = ["derive"] } 
serde_json = "1.0.134" 
rusqlite = { version = "0.32.1", features = ["bundled"] }
tokio = { version = "1", features = ["full"] }
