name: Rust Build and Release

on:
  push:
    tags:
      - 'v*'  # 当你推送以 'v' 开头的标签时触发，例如 v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Build release version
      run: cargo build --release --verbose  # 编译 release 版本

    - name: Run tests
      run: cargo test --verbose  # 可选步骤，确认代码是否通过测试

    - name: Create GitHub Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/your_project_name  # 你编译后的文件路径
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 会自动注入此 token，用于创建发布

